### PR TITLE
Update README.md

### PR DESCRIPTION
**Pull request by Sabarno-15102002**
# Description

Updated in Readme.md file and the logo has been updated according to the theme
Please include a summary of the change and which issue is fixed. Please also include relevant motivation and context. 

List any dependencies that are required for this change.

Fixes # (issue)

## Type of change

- [x] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] This change requires a documentation update

## Related Issues

List related issues here

## Additional Notes

Write additional notes here

## Screenshots

Place screenshots here

# Testing

Please describe the tests that you ran to verify your changes. Provide instructions so we can reproduce. Please also list any relevant details for your test configuration

- [ ] Test A
- [ ] Test B

**Test Environment**:
* Firmware version:
* Hardware:
* Toolchain:
* SDK:

# All Submissions

Before filling out the fields of the pull request, please make sure you meet the following requirements

* [x] I have read the [Contributor Guide](../../CONTRIBUTING.md)
* [x] I have read and agree to the [Code of Conduct](../../CODE_OF_CONDUCT.md)
* [x] My code follows the style guidelines of this project
* [x] I have performed a self-review of my own code
* [x] I have commented my code, particularly in hard-to-understand areas
* [x] I have made corresponding changes to the documentation
* [x] My changes generate no new warnings
* [ ] I have added tests that prove my fix is effective or that my feature works
* [x] New and existing unit tests pass locally with my changes
* [x] Any dependent changes have been merged and published in downstream modules

### CODE REVIEW

**Comment by vvelc** [comment]
Nice work!

It works pretty well.

Please check the link below. I think you could use this way to make it shorter.

https://github.blog/changelog/2021-11-24-specify-theme-context-for-images-in-markdown/

**Comment by Sabarno-15102002** [comment]
Thanks for the review.

I have tried to fix the issue earlier by using the theme specifier code fragments appending to the end of the image URL , but GitHub docs is showing that the method is deprecated and suggested this method.

Here is the link below of the GitHub documentation.

https://docs.github.com/en/get-started/writing-on-github/getting-started-with-writing-and-formatting-on-github/basic-writing-and-formatting-syntax#specifying-the-theme-an-image-is-shown-to

**Comment by vvelc** [comment]
Oh I see! I was unaware that the use of the method you suggested was deprecated.

Thank you very much for the feedback and for the collaboration in this project.

We hope you would like continue contributing! Have an excellent day!

**Review by vvelc — APPROVED** [review]
Great work!

**Pull request merged**
